### ISSUE TITLE
Error in API call : TypeError: any() takes exactly one argument (2 given)

### ISSUE THREAD

**Issue by dbarzin** [pandora-analysis/pandora#228]
When trying to get status on a task from pypandora : 

    poetry run pandora --url http://127.0.0.1:6100 --task_id "3667ad71-867d-48ad-8796-e2e782ec9b06" --seed "FLgUwo4VKZcb5qZowSB3u0GkpKyAKwOWAt_7-10nVa4" --all_workers

Got this error : 

    2023-02-24 12:29:58,757 root ERROR:Error in API call.
    Traceback (most recent call last):
      File "/home/pandora/pandora/website/web/generic_api.py", line 59, in wrapper
        res = func(*args, **kwargs)
      File "/home/pandora/pandora/website/web/generic_api.py", line 231, in get
        if not any(worker_name, all_workers):
    TypeError: any() takes exactly one argument (2 given)

Solution is to replace :

    if not any(worker_name, all_workers):

by 

     if not any([worker_name, all_workers]):

**Comment by Rafiot** [comment]
Good catch, thanks! Fixed.
