### ISSUE TITLE
preview randomly not working, again...

### ISSUE THREAD

**Issue by info-sic** [pandora-analysis/pandora#592]
Aloha,
my pandora-instance gets rebootet every night and starts with systemd. The start-exec includes an poetry run update --yes

Because of unknown reasons preview fails randomly (see also https://github.com/pandora-analysis/pandora/issues/93)
 ```
2024-04-25 07:57:41,662 extractor INFO:[a0eef483-5267-44e5-881d-3ca9fb821bd7] Runtime: 0.22s
File: /home/pandora/pandora/tasks/2024/04/a0eef483-5267-44e5-881d-3ca9fb821bd7/pandoratestmacro.docx

Unencrypted xlsm file

[Loading Cells]
[Starting Deobfuscation]
[END of Deobfuscation]
time elapsed: 0.1948859691619873
2024-04-25 07:57:41,760 xmldeobfuscator INFO:[a0eef483-5267-44e5-881d-3ca9fb821bd7] Runtime: 0.26s
2024-04-25 07:57:41,776 yara_signature_base INFO:[a0eef483-5267-44e5-881d-3ca9fb821bd7] Runtime: 0.36s
2024-04-25 07:57:41,835 observables INFO:[a0eef483-5267-44e5-881d-3ca9fb821bd7] Runtime: 0.41s
2024-04-25 07:57:41,827 yarahq_full INFO:[a0eef483-5267-44e5-881d-3ca9fb821bd7] Runtime: 0.40s
2024-04-25 07:57:41,847 hashlookup INFO:[a0eef483-5267-44e5-881d-3ca9fb821bd7] Runtime: 0.39s
2024-04-25 07:57:44,059 comodo INFO:[a0eef483-5267-44e5-881d-3ca9fb821bd7] Runtime: 2.65s
2024-04-25 07:57:56,460 qrcode INFO:[a0eef483-5267-44e5-881d-3ca9fb821bd7] Runtime: 15.02s
2024-04-25 07:58:41,420 preview ERROR:
Traceback (most recent call last):
  File "/home/pandora/pandora/pandora/workers/preview.py", line 15, in analyse
    task.file.convert()
  File "/home/pandora/pandora/pandora/file.py", line 276, in convert
    self.libreoffice_client.convert(inpath=str(self.path), outpath=f'{self.path}.pdf')
  File "/home/pandora/.cache/pypoetry/virtualenvs/pandora-Y9WI11B0-py3.10/lib/python3.10/site-packages/unoserver/client.py", line 98, in convert
    result = proxy.convert(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.10/xmlrpc/client.py", line 1179, in single_request
    resp = http_conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1375, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/home/pandora/pandora/pandora/workers/base.py", line 102, in _raise_timeout
    raise TimeoutError
TimeoutError
2024-04-25 07:58:41,421 preview WARNING:Unable to generate preview, this is suspicious: 
```

Error disappears after systemctl stop/start pandora.
Any ideas for a workaround?
Manu

**Comment by Rafiot** [comment]
Can you increase the timeout value in the settings of the preview worker?

**Comment by Rafiot** [comment]
Quick update on that: the file is huge (30+Mb), and generating the PDF in fact works. What fails is creating the images put of the exported PDF. I'm increasing the timeout until it work, but I'm not sure how practical it is.

**Comment by Rafiot** [comment]
yeah, seems it causes libreoffice processes to get stuck.

**Comment by Rafiot** [comment]
The problem with that approach was (I need to try it again) that the filenames weren't something I could set myself so they couldn't easily be seen on the web interface without reprocessing them individually. And We want the PDF export anyway, so this approach was more efficient.

But yes, as of now, it breaks the preview generator, I'll investigate.

**Comment by Rafiot** [comment]
just making sure, you restarted the workers? The settings will not be taken in account otherwise.

**Comment by Rafiot** [comment]
Yeah, I can see that, but the bar will not be doing anything more than moving somewhat randomly up to toe time it is done and the interface doesn't tell you to wait anymore.
